webproject/webapp/urls.py
from django.urls import path

from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('book/<int:book_id>/', views.details, name="details"),
    path('add/', views.book_add, name="book_add"),
    path('update/<int:id>/', views.update, name="update"),
    path('delete/<int:id>/',views.delete,name='delete'),

]

webproject/webproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("webapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webproject/webapp/models.py
from django.db import models


# Create your models here.
class books(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

webproject/webapp/forms.py
from django import forms
from .models import books


class bookform(forms.ModelForm):
    class Meta:
        model = books
        fields = ['name', 'desc', 'year', 'img']

webproject/webapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from webapp.models import books
from .forms import bookform


# Create your views here.
def index(request):
    var = books.objects.all()
    context = {
        'books_list': var
    }
    return render(request, 'index.html', context)


def details(request, book_id):
    book = books.objects.get(id=book_id)
    return render(request, "detail.html", {'book': book})


def book_add(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        book = books(name=name, desc=desc, year=year, img=img)
        book.save()
    return render(request, 'add.html')


def update(request, id):
    book = books.objects.get(id=id)
    form = bookform(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'book': book})


def delete(request, id):
    if request.method == 'POST':
        book = books.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request, 'delete.html')

webproject/webapp/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <label>enter your book name</label><input type="text" name="name"><br>
  <label>enter your book description</label><input type="text" name="desc"><br>
  <label>Enter book relaced year</label><input type="text" name="year"><br>
  <input type="file" name="img"><br>
  <input type="submit">
    {% endblock %}

</form>

</body>
</html>

webproject/webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
<nav class="navbar navbar-dark bg-success">
  <a class="navbar-brand" href="#">
   online book store
  </a>
</nav><br>
{% block body %}
{% endblock %}
</body>
</html>

webproject/webapp/templates/delete.html
<form method="post">
  {% csrf_token %}
are you sure delete the book?
  <input type="submit">
</form>

webproject/webapp/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-am-6">
            <img src="{{book.img.url}}" width="600" height="350">
        </div>
        <div class="col-am-6">
            <h2>{{book.name}}</h2>
            <h4>{{book.desc}}</h4>
            <h1>{{book.year}}</h1>
            <a class="btn btn-warning" href="{% url 'webapp:update' book.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'webapp:delete' book.id %}">delete</a>
        </div>
    </div>
</div>



{% endblock %}

webproject/webapp/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

webproject/webapp/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in books_list %}
        <div class="col-am-3">
            <div class="card" style="width:275px;">
              <img class="card-img-top" src="{{i.img.url}}" alt="..." height="130px">
                <div class="card-body">
                 <h5 class="card-title">{{i.name}}</h5>
                 <p class="card-text">{{i.desc}}</p>
                 <a href="{% url 'webapp:details' i.id %}" class="btn btn-success">show details</a>
                </div>
            </div>
        </div>
        &nbsp;
        {% endfor %}
    </div>
</div>
{% endblock %}